spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/WeConDB
    username: postgres
    password: 123456

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

